import type { Category, Card } from '@/types'

export const ASSETS = {
  catExclusive:      '/images/categories/catExclusive.png',
  catCards:          '/images/categories/catCards.png',
  catAnimals:        '/images/categories/catAnimals.png',
  catAnime:          '/images/categories/catAnime.png',
  catRoyal:          '/images/categories/catRoyal.png',
  catSignature:      '/images/categories/catSignature.png',
  catAbstract:       '/images/categories/catAbstract.png',
  catGames:          '/images/categories/catGames.png',
  visaLogo:          '/images/home/visaLogo.png',
  benefitMovie1:     '/images/home/benefitMovie1.png',
  benefitMovie2:     '/images/home/benefitMovie2.png',
  benefitFood1:      '/images/home/benefitFood1.png',
  benefitFood2:      '/images/home/benefitFood2.png',
  benefitTravel1:    '/images/home/benefitTravel1.png',
  benefitTravel2:    '/images/home/benefitTravel2.png',
  bestsellerCard:    '/images/home/bestsellerCard.png',
  secDivider:        '/images/home/secDivider.png',
  securityImg:       '/images/home/securityImg.png',
  securityImgMobile: '/images/home/securityImgMobile.png',
  convertGlow:       '/images/home/convertGlow.png',
  convertCard:       '/images/home/convertCard.png',
  convertDivider:    '/images/home/convertDivider.png',
  movieTicket:       '/images/home/movieTicket.png',
  rewardsBg:         '/images/home/rewardsBg.png',
  rewardsBgMobile:   '/images/home/rewardsBgMobile.png',
  clockIcon:         '/images/home/clockIcon.png',
  ctaBall:           '/images/home/ctaBall.png',
  payVisa:           '/images/payment/payVisa.png',
  payMastercard:     '/images/payment/payMastercard.png',
  payPhonePe:        '/images/payment/payPhonePe.png',
  payRazorpay:       '/images/payment/payRazorpay.png',
  payGPay:           '/images/payment/payGPay.png',
}

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'exclusive', label: 'Exclusive',  icon: ASSETS.catExclusive  },
  { id: 'cards',     label: 'Cards',      icon: ASSETS.catCards      },
  { id: 'animals',   label: 'Animals',    icon: ASSETS.catAnimals    },
  { id: 'anime',     label: 'Anime',      icon: ASSETS.catAnime      },
  { id: 'royal',     label: 'Royal',      icon: ASSETS.catRoyal      },
  { id: 'signature', label: 'Signature',  icon: ASSETS.catSignature  },
  { id: 'abstract',  label: 'Abstract',   icon: ASSETS.catAbstract   },
  { id: 'games',     label: 'Games',      icon: ASSETS.catGames      },
]

export const CAT_GRADIENTS: Record<string, { c1: string; c2: string }> = {
  exclusive: { c1: '#b88f1a', c2: '#3d2a06' },
  cards:     { c1: '#0f2a5a', c2: '#060e1e' },
  animals:   { c1: '#1a2f14', c2: '#060e04' },
  anime:     { c1: '#1c1c3a', c2: '#070712' },
  royal:     { c1: '#3a1414',
